# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: face_recognition.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x66\x61\x63\x65_recognition.proto\x12\x0f\x66\x61\x63\x65recognition\"*\n\x04\x46\x61\x63\x65\x12\x13\n\x0bperson_name\x18\x01 \x01(\t\x12\r\n\x05image\x18\x02 \x01(\x0c\"\x16\n\x05Image\x12\r\n\x05image\x18\x01 \x01(\x0c\"\"\n\rEmbedResponse\x12\x11\n\tembedding\x18\x01 \x03(\x02\"/\n\rPersonsInRoom\x12\x0f\n\x07persons\x18\x01 \x03(\t\x12\r\n\x05total\x18\x02 \x01(\x05\x32\x9b\x01\n\x0f\x46\x61\x63\x65Recognition\x12\x42\n\tEmbedFace\x12\x15.facerecognition.Face\x1a\x1e.facerecognition.EmbedResponse\x12\x44\n\nVerifyRoom\x12\x16.facerecognition.Image\x1a\x1e.facerecognition.PersonsInRoomB\x16\xaa\x02\x13\x46\x61\x63\x65RecognitionGrpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'face_recognition_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\023FaceRecognitionGrpc'
  _globals['_FACE']._serialized_start=43
  _globals['_FACE']._serialized_end=85
  _globals['_IMAGE']._serialized_start=87
  _globals['_IMAGE']._serialized_end=109
  _globals['_EMBEDRESPONSE']._serialized_start=111
  _globals['_EMBEDRESPONSE']._serialized_end=145
  _globals['_PERSONSINROOM']._serialized_start=147
  _globals['_PERSONSINROOM']._serialized_end=194
  _globals['_FACERECOGNITION']._serialized_start=197
  _globals['_FACERECOGNITION']._serialized_end=352
# @@protoc_insertion_point(module_scope)
