# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from transport.grpc.protos import face_recognition_pb2 as face__recognition__pb2


class FaceRecognitionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EmbedFace = channel.unary_unary(
                '/facerecognition.FaceRecognition/EmbedFace',
                request_serializer=face__recognition__pb2.Face.SerializeToString,
                response_deserializer=face__recognition__pb2.EmbedResponse.FromString,
                )
        self.VerifyRoom = channel.unary_unary(
                '/facerecognition.FaceRecognition/VerifyRoom',
                request_serializer=face__recognition__pb2.Image.SerializeToString,
                response_deserializer=face__recognition__pb2.PersonsInRoom.FromString,
                )


class FaceRecognitionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def EmbedFace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyRoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FaceRecognitionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EmbedFace': grpc.unary_unary_rpc_method_handler(
                    servicer.EmbedFace,
                    request_deserializer=face__recognition__pb2.Face.FromString,
                    response_serializer=face__recognition__pb2.EmbedResponse.SerializeToString,
            ),
            'VerifyRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyRoom,
                    request_deserializer=face__recognition__pb2.Image.FromString,
                    response_serializer=face__recognition__pb2.PersonsInRoom.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'facerecognition.FaceRecognition', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FaceRecognition(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EmbedFace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/facerecognition.FaceRecognition/EmbedFace',
            face__recognition__pb2.Face.SerializeToString,
            face__recognition__pb2.EmbedResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def VerifyRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/facerecognition.FaceRecognition/VerifyRoom',
            face__recognition__pb2.Image.SerializeToString,
            face__recognition__pb2.PersonsInRoom.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
