name: Docker Build CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
    - uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Docker image
      id: docker_build
      env:
        IMAGE_NAME: ghcr.io/${{ github.repository }}/roomvision-be
      run: |
        docker build ./roomvision-be/src --file ./roomvision-be/src/Dockerfile --tag $IMAGE_NAME:latest
        docker push $IMAGE_NAME:latest
