name: Docker Build CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./roomvision-be/src
          file: ./roomvision-be/src/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/roomvision-be:latest

      - name: Build & Push FaceRecognition
        uses: docker/build-push-action@v5
        with:
          context: ./roomvision-scripts
          file: ./roomvision-scripts/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/roomvision-facerecognition:latest
